version: "3"
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    ports:
      - 5432:5432
    networks:
      - msaw
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_database: 'postgres'

  directus:
    container_name: msaw_directus
    image: directus/directus:10.7.1
    ports:
      - 8050:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: "478database558225b888"
      SECRET: "478database558225b877bb"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "password"
      database_CLIENT: "pg"
      database_HOST: 'localhost'
      database_PORT: '5432'
      database_DATABASE: 'postgres'
      database_USER: 'postgres'
      database_PASSWORD: 'postgres'
      WEBSOCKETS_ENABLED: true
    networks:
      - msaw
    depends_on:
      - database
    env_file:
      - .env

networks:
  msaw: 
     name: MSAW
     driver: bridge

      
